<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <h2>Galeria de fotos</h2>
        <div class="row">
            <form action="subir.php" method="POST" enctype="multipart/form-data">
                <div class="form-group">
                    <input type="file" class="form-control-file" name="foto" id="foto">
                    <button type="submit" class="btn btn-primary">Subir</button>
                </div>
            </form>
        </div>
        <div class="row row-cols-md-4 row-cols-sm-2 row-cols-1">
            <?php
            foreach ($arrayFotos as $foto) {
                ?>
                <div class="col mb-4">
                    <div class="card">
                        <div class="card-header">
                            <?= $foto ?>
                        </div>
                        <div class="card-body">
                            <img src="<?= $dir . $foto ?>" class="card-img-top" alt="<?= $foto ?>">
                            <p class="card-text"><?= filesize($dir . $foto) ?> bytes</p>
                        </div>
                    </div>
                </div>

            <?php
            }
            ?>
        </div>

</body>

</html>