<?php require_once "Ti.php"; ?>
<?php Ti::extend("MainView.phtml"); ?>

<?php Ti::startBlock("content"); ?>
<?php $deporteSeleccionado = $_REQUEST["deporteSeleccionado"] ?? ""; ?>
<div class="row">
    <form action="index.php" method="GET">
        <div class="form-group">
            <input type="hidden" name="controller" value="listado">
            <select class="form-control" name="deporteSeleccionado">
                <option value="">Todos</option>
                <?php
                foreach ($data["deportes"] as $deporte) {
                    ?>
                    <option <?php if ($deporteSeleccionado == $deporte->id) echo "selected"; ?> value="<?= $deporte->id ?>"><?= $deporte->nombre ?></option>
                <?php
                }
                ?>
            </select>
            <button type="submit" class="btn btn-primary">Buscar</button>
        </div>
    </form>
</div>
<div class="row row-cols-1 row-cols-md-2">
    <?php
    foreach ($data["deportistas"] as $deportista) {
        if ($data["deportes"][$deportista->id_deporte]->id == $deporteSeleccionado || $deporteSeleccionado == "") {
            ?>
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="assets/fotos/<?= $deportista->img ?>" class="card-img" alt="<?= $deportista->nombre ?>">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title"><?= $deportista->nombre ?></h5>
                            <p class="card-text"><?= isset($deportista->nombre_local) ? " ($deportista->nombre_local) " : "$deportista->nombre" ?> tiene <?= $deportista->getEdad() ?> años. Compite en <?= $data["deportes"][$deportista->id_deporte]->nombre ?>.</p>
                            <p class="card-text"><small class="text-muted"><a href="index.php?controller=informacion&id=<?= $deportista->id ?>">Para más información</a></small></p>
                        </div>
                    </div>
                </div>
            </div>
    <?php
        }
    }
    ?>
</div>
<div class="row">
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <?php
            for ($i = 1; $i <= $data["numPaginas"]; $i++) {
                ?>
                <li class="page-item"><a class="page-link" href="index.php?pagina=<?= $i ?>&deporteSeleccionado=<?= $deporteSeleccionado ?>"><?= $i ?></a></li>
            <?php
            }
            ?>
        </ul>
    </nav>
</div>
<?php Ti::endBlock(); ?>
<?php Ti::endExtend() ?>