<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Exito</title>
</head>

<body>
    <div style="margin:3px 20px;">
        <h1>Instalación de app Planetas</h1>
        <hr>
        <p>Se ordenó la ejecución del script de creación de la bd.</p>
        <p>Se creó el fichero config.ini con los parámetros de conexión</p>
        <a href=".">Entrar a la app</a>
    </div>
</body>

</html>