<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Modificar Planeta</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page"><a href=".">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Modificar planeta</li>
        </ol>
        <?php if ($error_msg) { ?>
            <div class="alert alert-danger" role="alert">
                <?= $error_msg ?>
            </div>
        <?php } ?>
        <form action="?controller=modificacion" method="POST">
            <input type="hidden" name="id" value="<?= $id ?>">
            <div class="form-group row">
                <label for="nombreinput" class="col-md-3">Nombre: </label>
                <input type="text" class="form-control col-md-9" id="nombreinput" name="nombre" value="<?= $planeta->nombre ?>">
            </div>
            <div class="form-group row">
                <label for="pesoinput" class="col-md-3">Peso:</label>
                <input type="number" class="form-control col-md-9" id="pesoinput" min="0" name="peso" value="<?= $planeta->peso ?>">
            </div>
            <div class="form-group row">
                <label for="radioinput" class="col-md-3">Radio:</label>
                <input type="number" class="form-control col-md-9" id="radioinput" min="0" name="radio" value="<?= $planeta->radio ?>">
            </div>
            <div class="row">
                <div class="offset-md-3 col-md-9"><button type="submit" class="btn btn-primary">Enviar</button> <a href="?controller=listado" class="btn btn-secondary">Cancelar</a>
                </div>
        </form>
    </div>
</body>

</html>