<?php
global $URL_PATH;
\dawfony\Ti::extend("view/mainview.phtml");
\dawfony\Ti::startBlock("content");
?>

<?php if (isset($_SESSION["login"])) : ?>
  <div class="row container">
    <h3>
      Hola <?= $usuario->nombre ?>
    </h3>
  </div>
  <a href="<?= $URL_PATH ?>/cerrarSesion" class="btn btn-outline-danger mb-2">Cerrar Sesión</a>

<?php endif ?>
<!-- ********************** listado ******************************************* -->

<div class="row">
  <?php foreach ($viajes as $viaje) : ?>
    <div class="col-md-6 pb-2">
      <div class="card">
        <img class="card-img-top img-fluid" src="<?= $viaje->imagenurl ?>" alt="<?= $viaje->titulo ?>">
        <div class="card-body">
          <h5 class="card-title"><?= $viaje->titulo ?></h5>
          <p class="card-text"><del>Precio: <?= $viaje->precio ?></del></p>
          <?php if (isset($_SESSION["login"])) : ?>
            <p class="card-text"><strong>Precio privado: <?= $viaje->precioprivado ?>€</strong></p>
            <a href="javascript:void(0)" onclick="verDescripcion(<?= $viaje->id ?>)" class="btn btn-primary">Ver descripción</a>
          <?php else : ?>
            <p class="card-text"><strong>Precio privado: ??</strong></p>
            <a href="<?= $URL_PATH ?>/login" class="btn btn-primary">Inicia sesión para ver detalles</a>
          <?php endif ?>

        </div>
      </div>
    </div>
  <?php endforeach ?>
</div>

<!-- ********************** paginación **************************************** -->

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center mt-4">
    <li class="page-item">
      <a class="page-link" href="<?= $URL_PATH ?>/" aria-label="Primera">
        <span aria-hidden="true">1 - Primera</span>
      </a>
    </li>
    <?php if (($pagina - 1) != 0) : ?>
      <li class="page-item"><a class="page-link" href="<?= $URL_PATH ?>/pagina/<?= $pagina - 1 ?>"><?= $pagina - 1 ?></a></li>
    <?php endif ?>
    <li class="page-item active" aria-current="page">
      <span class="page-link">
        <?= $pagina ?>
        <span class="sr-only">(current)</span>
      </span>
    </li>
    <?php if (($pagina + 1) <= $numPaginas) : ?>
      <li class="page-item"><a class="page-link" href="<?= $URL_PATH ?>/pagina/<?= $pagina + 1 ?>"><?= $pagina + 1 ?></a></li>
    <?php endif ?>
    <li class="page-item">
      <a class="page-link" href="<?= $URL_PATH ?>/pagina/<?= $numPaginas ?>" aria-label="Ultima">
        <span aria-hidden="true"><?= $numPaginas ?> - Última</span>
      </a>
    </li>
  </ul>
</nav>


<!-- ********************** Modal ********************************************* -->
<script>
  function verDescripcion(viajeid) {
    console.log("En verDescipcion del viaje #" + viajeid); // mensaje de depuración
    datosViaje(viajeid);
    // Esto es jquery, copiado de la documentación de bootstrap.
    $('#viajeModal').modal('show'); // mostrar div oculto de manera modal. 
  }
</script>

<div class="modal fade" id="viajeModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="titulo">titulo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p id="descripcion">descripcion</p>
        <p id="precioprivado" class="text-success font-weight-bold">precioprivado</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

<?php
\dawfony\Ti::endBlock();
\dawfony\Ti::endExtend();
?>