<?php

use \dawfony\Ti;

global $URL_PATH;
Ti::extend("view/main.phtml"); ?>
<?php Ti::startBlock("extrahead"); ?>
<script src="<?= $URL_PATH ?>/js/carro.js"></script>

<?php Ti::endBlock(); ?>

<?php Ti::startBlock("content"); ?>
<div class="table-responsive">
    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
                <th scope="col"></th>
                <th scope="col">Producto</th>
                <th scope="col">Cantidad</th>
                <th scope="col">Precio unitario</th>
                <th scope="col">Precio total</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody id="tablaProductos">
            <?php foreach ($cesta as $producto) : ?>
                <tr id="<?= $producto->id_producto ?>">
                    <td class="w-25"><img src="<?= $URL_PATH ?>/assets/photos/<?= $producto->foto ?>" class="img-fluid w-25" alt="<?= $producto->foto ?>"></td>
                    <td><?= $producto->nombre ?></td>
                    <td>
                        <button type="button" id="+<?= $producto->id_producto ?>" class="btn btn-outline-primary" onclick="modificarCantidad(<?= $producto->id_producto ?>, '+')"><i class="fa fa-plus"></i></button>
                        <span id="cantidad<?= $producto->id_producto ?>"><?= $producto->cantidad ?></span>
                        <button type="button" id="-<?= $producto->id_producto ?>" class="btn btn-outline-primary" onclick="modificarCantidad(<?= $producto->id_producto ?>, '-')"><i class="fa fa-minus"></i></button>
                    </td>
                    <td><?= $producto->precio ?>€</td>
                    <td id="precioTotal<?= $producto->id_producto ?>"><?= $producto->cantidad * $producto->precio ?>€</td>
                    <td><a href="javascript:void(0)" onclick="borrarProducto('<?= $producto->id_producto ?>')"><i class="fa fa-trash text-danger"></i></a></td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</div>
<div class="row float-right">
    <div class="col-3 p-2">
        <a href="<?= $URL_PATH ?>/tramitarPedido" class="btn btn-success">Pagar</a>
    </div>
    <div class="col-7 ml-4 alert alert-success">
        Total: <span id="pedidoTotal" class="font-weight-bold"><?= $pedidoTotal ?></span>€
    </div>

</div>
<?php Ti::endBlock(); ?>
<?php Ti::endExtend() ?>