<?php

use \dawfony\Ti;

global $URL_PATH;
Ti::extend("view/main.phtml"); ?>
<?php Ti::startBlock("extrahead"); ?>
<script src="<?= $URL_PATH ?>/js/modificarCantidad.js"></script>

<?php Ti::endBlock(); ?>

<?php Ti::startBlock("content"); ?>
<div class="table-responsive">
    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
                <th scope="col"></th>
                <th scope="col">Producto</th>
                <th scope="col">Cantidad</th>
                <th scope="col">Precio unitario</th>
                <th scope="col">Precio total</th>
            </tr>
        </thead>
        <tbody id="tablaProductos">
            <?php foreach ($cesta as $producto) : ?>
                <tr>
                    <td class="w-25"><img src="<?= $URL_PATH ?>/assets/photos/<?= $producto->foto ?>" class="img-fluid" alt="<?= $producto->foto ?>"></td>
                    <td><?= $producto->nombre ?></td>
                    <td>
                        <button type="button" id="+<?= $producto->id_producto ?>" class="btn btn-outline-primary" onclick="modificarCantidad(<?= $producto->id_producto ?>, '+')"><i class="fa fa-plus"></i></button>
                        <span id="cantidad<?= $producto->id_producto ?>"><?= $producto->cantidad ?></span>
                        <button type="button" id="-<?= $producto->id_producto ?>" class="btn btn-outline-primary" onclick="modificarCantidad(<?= $producto->id_producto ?>, '-')"><i class="fa fa-minus"></i></button>
                    </td>
                    <td><?= $producto->precio ?>€</td>
                    <td><?= $producto->cantidad * $producto->precio ?>€</td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</div>
<?php Ti::endBlock(); ?>
<?php Ti::endExtend() ?>