<?php

use \dawfony\Ti;

global $URL_PATH;
Ti::extend("view/main.phtml"); ?>
<?php Ti::startBlock("extrahead"); ?>
<style>
    #contenedorCarrito {
        position: fixed;
        top: 5%;
        right: 4%;
        z-index: 1
    }
</style>
<script src="<?= $URL_PATH ?>/js/comprar.js"></script>
<?php Ti::endBlock(); ?>

<?php Ti::startBlock("content"); ?>
<div class="row">
    <?php foreach ($productos as $producto) : ?>
        <div class="card col-md-3 pb-2 mt-3">
            <img src="<?= $URL_PATH ?>/assets/photos/<?= $producto->foto ?>" class="card-img-top img-fluid" alt="<?= $producto->foto ?>">
            <div class="card-body">
                <h5 class="card-title text-uppercase font-italic font-weight-bold"><?= $producto->nombre ?></h5>
                <p class="card-text"><?= $producto->descripcion ?></p>
            </div>
            <div class="card-footer bg-transparent border-success">
                <a href="javascript:void(0)" onclick="comprar(<?= $producto->id_producto ?>)" class="btn btn-outline-success">Comprar <?= $producto->precio ?>€</a>
            </div>
        </div>
    <?php endforeach ?>
</div>

<div class="text-center" id="contenedorCarrito">
    <a href="#" class="text-danger" style="font-size: 35px">
        <i class="fa fa-shopping-cart"></i><span id="numArticulos"> <?= $numProductos ?></span>
    </a>
    <div class="d-none">

    </div>
</div>

<?php Ti::endBlock(); ?>
<?php Ti::endExtend() ?>