<?php

use \dawfony\Ti;

global $URL_PATH;
Ti::extend("view/main.phtml"); ?>
<?php Ti::startBlock("extrahead"); ?>
<style>
    #contenedorCarrito {
        position: fixed;
        top: 0%;
        right: 0%;
        z-index: 1;
        height: 100%;
        width: 10%;
    }

    #contenedorProductos {
        display: none;
    }
</style>
<script src="<?= $URL_PATH ?>/js/comprar.js"></script>
<script src="<?= $URL_PATH ?>/js/carro.js"></script>
<?php Ti::endBlock(); ?>

<?php Ti::startBlock("content"); ?>
<div class="row mr-5">
    <?php foreach ($productos as $producto) : ?>
        <div class="card col-md-3 pb-2 mt-3">
            <img src="<?= $URL_PATH ?>/assets/photos/<?= $producto->foto ?>" class="card-img-top img-fluid" alt="<?= $producto->foto ?>">
            <div class="card-body">
                <h5 class="card-title text-uppercase font-italic font-weight-bold"><?= $producto->nombre ?></h5>
                <p class="card-text"><?= $producto->descripcion ?></p>
            </div>
            <div class="card-footer bg-transparent border-success">
                <a href="javascript:void(0)" onclick="comprar(<?= $producto->id_producto ?>)" class="btn btn-outline-success">Comprar <?= $producto->precio ?>€</a>
                <input type="number" class="form-control" id="<?= $producto->id_producto ?>" min="1" value="1">
            </div>
        </div>
    <?php endforeach ?>
</div>

<div class="text-center bg-info text-light" id="contenedorCarrito">
    <div id="carro">
        <a href="javascript:void(0)" onclick="mostrarCarro()" class="text-danger" style="font-size: 35px">
            <i class="fa fa-shopping-cart"></i><span id="numArticulos"> <?= $numProductos ?></span>
        </a>
    </div>
    <div id="contenedorProductos">
        <a href="<?= $URL_PATH ?>/pedido" class="btn btn-success">Tramitar Pedido</a>
        <?php foreach ($cesta as $producto) : ?>
            <div class="mt-1">
                <img src="<?= $URL_PATH ?>/assets/photos/<?= $producto->foto ?>" class="imagen-cesta w-25" alt="<?= $producto->foto ?>">
                <div class="info">
                    (x<?= $producto->cantidad ?>)<?= $producto->nombre ?> - <?= $producto->precio ?>€
                </div>
            </div>
        <?php endforeach ?>
    </div>
</div>

<?php Ti::endBlock(); ?>
<?php Ti::endExtend() ?>