<?php

use \dawfony\Ti;

global $URL_PATH;
?>
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- scripts -->
    <script>
        var URL_PATH = "<?= $URL_PATH ?>"; // Pasamos el URL_PATH de php a Javascript.
    </script>
    <?php Ti::startBlock("extrahead"); ?>
    <?php Ti::endBlock() ?>
    <title>
        <?php Ti::startBlock("title"); ?>
        <?= $data["title"] ?>
        <?php Ti::endBlock() ?>
    </title>
</head>

<body>

    <div class="jumbotron bg-info text-light">
        <div class="container text-center">
            <h1 class="display-5">TIENDA</h1>
            <p class="lead">Amazon en sus inicios</p>
        </div>
    </div>

    <div class="row container">
        <?php Ti::startBlock("content"); ?>
        <?php Ti::endBlock() ?>
    </div>
</body>

</html>