<?php

use \dawfony\Ti;

global $URL_PATH;
Ti::extend("view/main.phtml"); ?>
<?php Ti::startBlock("extrahead"); ?>
<script>
    var usuarioAutenticado = false;
</script>
<script src="<?= $URL_PATH ?>/js/registro.js"></script>
<script src="<?= $URL_PATH ?>/js/pedido.js"></script>

<?php Ti::endBlock(); ?>

<?php Ti::startBlock("content"); ?>
<ul class="nav nav-tabs mb-3">
    <li class="nav-item">
        <a href="#formularioRegistro" class="nav-link active" data-toggle="tab">Datos Contacto</a>
    </li>
    <li class="nav-item">
        <a href="#formularioLogin" class="nav-link" data-toggle="tab">Logearse</a>
    </li>
</ul>
<div class="tab-content">
    <div class="tab-pane fade show active" id="formularioRegistro">
        <div class="form-group row">
            <label for="email" class="col-sm-2 col-form-label">Email</label>
            <div class="col-7">
                <input type="text" name="email" class="form-control" id="email" oninput="emailExiste()">
            </div>
        </div>
        <div class="form-group row">
            <label for="password" class="col-sm-2 col-form-label">Contraseña</label>
            <div class="col-7">
                <input type="password" name="password" class="form-control" id="password" oninput="comprobarContrasena()">
            </div>
        </div>
        <div class="form-group row">
            <label for="password2" class="col-sm-2 col-form-label">Repite contraseña</label>
            <div class="col-7">
                <input type="password" name="password2" class="form-control" id="password2" oninput="comprobarRepetirContrasena()">
            </div>
        </div>
        <div class="form-group row">
            <label for="nombre" class="col-sm-2 col-form-label">Tu nombre</label>
            <div class="col-7">
                <input type="text" name="nombre" class="form-control" id="nombre" oninput="comprobarNombre()">
            </div>
        </div>
        <div class="form-group row">
            <label for="direccion" class="col-sm-2 col-form-label">Dirección</label>
            <div class="col-7">
                <input type="text" name="direccion" class="form-control" id="direccion" oninput="comprobarDireccion()">
            </div>
        </div>
    </div>
    <div class="tab-pane fade" id="formularioLogin">
        <div class="form-group row">
            <label for="emailLogin" class="col-sm-2 col-form-label">Email</label>
            <div class="col-7">
                <input type="text" name="emailLogin" class="form-control" id="emailLogin">
            </div>
        </div>
        <div class="form-group row">
            <label for="passwordLogin" class="col-sm-2 col-form-label">Contraseña</label>
            <div class="col-7">
                <input type="password" name="passwordLogin" class="form-control" id="passwordLogin">
            </div>
        </div>
        <div class="form-group row">
            <button class="btn btn-success" onclick="comprobarLogin()">Logearse</button>
        </div>
    </div>
</div>
<!-- mostrar cesta -->

<div class="form-group row">
    <button class="btn btn-success" onclick="procesarPedido()">PAGAR</button>
</div>
<?php Ti::endBlock(); ?>
<?php Ti::endExtend() ?>