<?php

use \dawfony\Ti;

global $URL_PATH;
Ti::extend("view/main.phtml"); ?>
<?php Ti::startBlock("extrahead"); ?>
<!-- <script src="<?= $URL_PATH ?>/js/usuario.js"></script> -->

<?php Ti::endBlock(); ?>

<?php Ti::startBlock("content"); ?>
<!-- <ul class="nav nav-pills">
    <li><a class="btn btn-primary mr-1 active" data-toggle="pill" href="#formularioRegistro">Datos Contacto</a></li>
    <li><a class="btn btn-info" data-toggle="pill" href="#formularioLogin">Logearse</a></li>
</ul>

<div class="tab-content">
    <div id="formularioRegistro" class="tab-pane fade show active">
        <h3>HOME</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </div>
    <div id="formularioLogin" class="tab-pane fade">
        <h3>Menu 1</h3>
        <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>
</div> -->
<ul class="nav nav-tabs mb-3">
    <li class="nav-item">
        <a href="#formularioRegistro" class="nav-link active" data-toggle="tab">Datos Contacto</a>
    </li>
    <li class="nav-item">
        <a href="#formularioLogin" class="nav-link" data-toggle="tab">Logearse</a>
    </li>
</ul>
<div class="tab-content">
    <div class="tab-pane fade show active" id="formularioRegistro">
        <div class="form-group row">
            <label for="email" class="col-sm-2 col-form-label">Email</label>
            <div class="col-7">
                <input type="email" name="email" class="form-control" id="email">
            </div>
        </div>
        <div class="form-group row">
            <label for="password" class="col-sm-2 col-form-label">Contraseña</label>
            <div class="col-7">
                <input type="password" name="password" class="form-control" id="password">
            </div>
        </div>
        <div class="form-group row">
            <label for="password2" class="col-sm-2 col-form-label">Repite contraseña</label>
            <div class="col-7">
                <input type="password" name="password2" class="form-control" id="password2">
                <small class="form-text text-danger" id="errorContrasena"></small>
            </div>
        </div>
        <div class="form-group row">
            <label for="nombre" class="col-sm-2 col-form-label">Tu nombre</label>
            <div class="col-7">
                <input type="text" name="nombre" class="form-control" id="nombre">
                <small class="form-text text-danger" id="errorNombre"></small>
            </div>
        </div>
        <div class="form-group row">
            <label for="direccion" class="col-sm-2 col-form-label">Dirección</label>
            <div class="col-7">
                <input type="text" name="direccion" class="form-control" id="direccion">
                <small class="form-text text-danger" id="errorDireccion"></small>
            </div>
        </div>
    </div>
    <div class="tab-pane fade" id="formularioLogin">
    <div class="form-group row">
        <label for="emailLogin" class="col-sm-2 col-form-label">Email</label>
        <div class="col-7">
            <input type="text" name="emailLogin" class="form-control" id="emailLogin">
        </div>
    </div>
    <div class="form-group row">
        <label for="passwordLogin" class="col-sm-2 col-form-label">Contraseña</label>
        <div class="col-7">
            <input type="password" name="passwordLogin" class="form-control" id="passwordLogin">
        </div>
    </div>
    </div>
</div>
<?php Ti::endBlock(); ?>
<?php Ti::endExtend() ?>