-- MySQL Script generated by MySQL Workbench
-- Thu Jan 30 17:34:48 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tienda
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tienda` ;

-- -----------------------------------------------------
-- Schema tienda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tienda` DEFAULT CHARACTER SET utf8 ;
USE `tienda` ;

-- -----------------------------------------------------
-- Table `tienda`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda`.`producto` ;

CREATE TABLE IF NOT EXISTS `tienda`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(200) NULL,
  `foto` VARCHAR(45) NULL,
  `precio` DOUBLE NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda`.`usuario` ;

CREATE TABLE IF NOT EXISTS `tienda`.`usuario` (
  `login` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `contrasena` VARCHAR(200) NULL,
  `direccion` VARCHAR(200) NULL,
  PRIMARY KEY (`login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda`.`pedido` ;

CREATE TABLE IF NOT EXISTS `tienda`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pedido`, `id_usuario`),
  INDEX `id_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tienda`.`usuario` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`producto-pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda`.`producto-pedido` ;

CREATE TABLE IF NOT EXISTS `tienda`.`producto-pedido` (
  `id_pedido` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`id_pedido`, `id_producto`),
  INDEX `id_producto_idx` (`id_producto` ASC),
  CONSTRAINT `id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `tienda`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `tienda`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`cesta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda`.`cesta` ;

CREATE TABLE IF NOT EXISTS `tienda`.`cesta` (
  `id_visitante` VARCHAR(100) NULL,
  `id_producto` INT NULL,
  `cantidad` INT NULL,
  `id_cesta` INT NOT NULL,
  INDEX `id_producto_idx` (`id_producto` ASC),
  PRIMARY KEY (`id_cesta`),
  CONSTRAINT `id_producto_cesta`
    FOREIGN KEY (`id_producto`)
    REFERENCES `tienda`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
