<?php

use \dawfony\Ti;

/* extract($data); */

global $URL_PATH;
Ti::extend("view/MainView.phtml"); ?>

<?php Ti::startBlock("content"); ?>
<h2>Nuevo Post</h2>
<div class="col-md-6">
    <form action="<?=$URL_PATH?>/publicarPost" method="POST">
        <div class="form-group">
            <label for="resumen">Resumen</label>
            <textarea class="form-control" id="resumen" name="resumen" rows="2"></textarea>
        </div>
        <div class="form-group">
            <label for="texto">Texto Completo</label>
            <textarea class="form-control" id="texto" name="texto" rows="5"></textarea>
        </div>
        <div class="form-group row">
            <div class="col-md-6">
                <label for="categoria">Escoge Categoría:</label>
                <select id="categoria" name="categoria_id">
                    <?php foreach ($categorias as $categoria) : ?>
                        <option value="<?= $categoria["id"] ?>"><?= $categoria["descripcion"] ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="col-md-6">
                <label for="filefoto">Sube una foto:</label>
                <input type="file" class="form-control-file" id="filefoto" name="foto">
            </div>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Enviar</button>
        </div>
    </form>
</div>


<?php Ti::endBlock(); ?>
<?php Ti::endExtend() ?>