<?php

use \dawfony\Ti;

extract($data);
global $URL_PATH;
Ti::extend("view/MainView.phtml"); ?>

<?php Ti::startBlock("content"); ?>
<?php foreach ($posts as $post) : ?>
    <div class="row mt-4">
        <div class="col-md-3">
            <img src="<?= $URL_PATH ?>/assets/photos/<?= $post->foto ?>" alt="<?= $post->foto ?>" class="img-fluid">
        </div>
        <div class="col-md-7">
            <?= $post->resumen ?><br>
            <div class="row">
                <div class="col-md-6">
                    <a class="btn btn-info" href=" <?= $URL_PATH ?>/post/<?= $post->id ?>" role="button">Ver más</a>
                </div>
                <div class="col-md-5">
                    <?php if (isset($_SESSION["login"])) : ?>
                        <a href="javascript:void(0)" onclick="likeClicked(<?= $post->id ?>)">
                        <?php endif ?>
                        <?php /* El atributo id del elemento del corazón tiene como sufijo el id del post */ ?>
                        <i id="likecorazon<?= $post->id ?>" class="fa fa-heart <?= ($post->like ? " text-danger" : "") ?>"></i>
                        <?php if (isset($_SESSION["login"])) : ?>
                        </a>
                    <?php endif ?>
                    <?php /* Lo mismo para el elemento que contiene la cuenta de likes:
                             su atributo id contiene como sufijo el id del post */ ?>
                    <span id="likecontador<?= $post->id ?>">
                        <?= $post->numLikes ?>
                    </span>
                    <i class="fa fa-comments"></i> <?= $post->numComentarios ?>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <a href="<?= $URL_PATH ?>/perfil/<?= $post->usuario_login ?>"><?= $post->usuario_login ?></a> en <?= $post->descripcion ?> a <?= $post->fecha ?>.
        </div>
    </div>
<?php endforeach ?>
<nav aria-label="Page navigation" class="mt-2">
    <ul class="pagination justify-content-center">
        <li class="page-item<?= ($pagina - 1 < 1 ? " disabled" : "") ?>">
            <a class="page-link" href="<?= $ruta . ($pagina - 1) ?>" tabindex="-1"><i class="fa fa-reply"></i></a>
        </li>
        <li class="page-item active">
            <a class="page-link" href="#"><?= $pagina ?></a>
        </li>
        <li class="page-item<?= ($pagina + 1 > $numPaginas ? " disabled" : "") ?>">
            <a class="page-link" href="<?= $ruta . ($pagina + 1) ?>"><i class="fa fa-share"></i></a>
        </li>
    </ul>
</nav>

<?php Ti::endBlock(); ?>
<?php Ti::endExtend() ?>