<?php

use \dawfony\Ti;

extract($data);
global $URL_PATH;
Ti::extend("view/MainView.phtml"); ?>

<?php Ti::startBlock("content"); ?>
<?php foreach ($posts as $post) : ?>
    <div class="row mt-4">
        <div class="col-md-3">
            <img src="<?= $URL_PATH ?>/assets/photos/<?= $post->foto ?>" alt="<?= $post->foto ?>" class="img-fluid">
        </div>
        <div class="col-md-7">
            <?= $post->resumen ?><br>
            <div class="row">
                <!-- falta escoger tamaño para el boton y luego añadir div con otro tamaño para el like y comentario, mirar código -->
                <a class="btn btn-info" href=" <?= $URL_PATH ?>/post/<?= $post->id ?>" role="button">Ver más</a>
            </div>

        </div>
        <div class="col-md-2">
            <?= $post->usuario_login ?> en <?= $post->descripcion ?> a <?= $post->fecha ?>.
        </div>
    </div>
<?php endforeach ?>

<?php Ti::endBlock(); ?>
<?php Ti::endExtend() ?>