<?php

use \dawfony\Ti;

extract($data);
Ti::extend("view/MainView.phtml"); ?>

<?php Ti::startBlock("content"); ?>
<form class="col-md-8 mx-auto mt-5" method="POST" action="<?= $data["URL_PATH"] ?>/login">
    <div class="form-group row">
        <label for="login" class="col-sm-2 col-form-label">Login</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="login">
        </div>
    </div>
    <div class="form-group row">
        <label for="password" class="col-sm-2 col-form-label">Contraseña</label>
        <div class="col-sm-10">
            <input type="password" class="form-control" id="password">
        </div>
    </div>
    
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Logearse</button>
        </div>
    </div>
</form>

<?php Ti::endBlock(); ?>
<?php Ti::endExtend() ?>