<?php

use \dawfony\Ti;

extract($data);
global $URL_PATH;
session_start();
?>
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="vendor/twbs/bootstrap/dist/css/bootstrap.min.css"> -->
    <title>
        <?php Ti::startBlock("title"); ?>
        <?= $data["title"] ?>
        <?php Ti::endBlock() ?>
    </title>
</head>

<body>
    <div class="container">
        <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <h1 class="display-4">SocialDAW</h1>
                <p class="lead">Red Social de anime, jpop y kpop</p>
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="<?= $URL_PATH ?>/">Lo último</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <?php if (isset($_SESSION["login"])) : ?>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $URL_PATH ?>/siguendo">Siguiendo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $URL_PATH ?>/perfil">Tu perfil</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-outline-danger" href="<?= $URL_PATH ?>/cerrarsesion">Cerrar Sesión</a>
                        </li>
                    <?php else : ?>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $URL_PATH ?>/registro">Registrarse</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $URL_PATH ?>/login">Login</a>
                        </li>
                    <?php endif ?>

                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
                </form>
            </div>
        </nav>
        <?php Ti::startBlock("content"); ?>
        <?php Ti::endBlock() ?>
    </div>
</body>

</html>