<?php

use \dawfony\Ti;

extract($data);
global $URL_PATH;
Ti::extend("view/MainView.phtml"); ?>

<?php Ti::startBlock("content"); ?>
<div class="row">
    <h3><?= $post->resumen ?></h3>
</div>
<div class="row">
    <div class="col-md-2">
        <img src="assets/photos/<?= $post->foto ?>" alt="<?= $post->foto ?>" class="img-fluid">
    </div>
    <div class="col-md-8">
        <?= $post->texto ?>
    </div>
    <div class="col-md-1">
        <?= $post->usuario_login ?> en <?= $post->descripcion ?> a <?= $post->fecha ?>.
    </div>
    <div class="col-md-1">

    </div>
</div>

<?php Ti::endBlock(); ?>
<?php Ti::endExtend() ?>