<?php

use \dawfony\Ti;

extract($data);
global $URL_PATH;
Ti::extend("view/MainView.phtml"); ?>

<?php Ti::startBlock("content"); ?>
<div class="row mt-2 mr-3 ml-3">
    <h3><?= $post->resumen ?></h3>
</div>
<div class="row">
    <div class="col-md-4">
        <img src="<?= $URL_PATH ?>/assets/photos/<?= $post->foto ?>" alt="<?= $post->foto ?>" class="img-fluid">
    </div>
    <div class="col-md-5">
        <?= $post->texto ?>
    </div>
    <div class="col-md-1">
        <a href="<?= $URL_PATH ?>/perfil/<?= $post->usuario_login ?>"><?= $post->usuario_login ?></a> en <?= $post->descripcion ?> a <?= $post->fecha ?>.
    </div>
    <div class="col-md-2">
        <?php if (isset($_SESSION["login"])) : ?>
            <?php if ($_SESSION["login"] != $post->usuario_login) : ?>
                <?php if (!$esSeguidor) : ?>
                    <a href="<?= $URL_PATH ?>/seguir/<?= $post->usuario_login ?>/<?= $post->id ?>" class="btn btn-primary">Seguir</a>
                <?php else : ?>
                    <a href="<?= $URL_PATH ?>/dejarSeguir/<?= $post->usuario_login ?>/<?= $post->id ?>" class="btn btn-danger">Dejar de seguir</a>
                <?php endif ?>
            <?php endif ?>
        <?php endif ?>
        <div>Siguiendo: <?= $siguiendo ?>. Seguidores: <?= $seguidores ?>.</div>
    </div>
</div>
<?php if (isset($_SESSION["login"])) : ?>
    <div class="row col-md-6">
        <form action="<?= $URL_PATH ?>/post/<?= $post->id ?>/comentario" method="POST">
            <div class="form-group">
                <h2>Comentarios</h2>
                <textarea class="form-control" id="comentario" name="comentario" rows="2"></textarea>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Enviar</button>
            </div>
        </form>
    </div>
<?php endif ?>
<?php if (isset($comentarios)) : ?>
    <div class="row mt-3">
        <?php foreach ($comentarios as $comentario) : ?>
            <div class="col-md-8">
                <?= $comentario->texto ?>
            </div>
            <div class="col-md-2">
                <a href="<?= $URL_PATH ?>/perfil/<?= $comentario->usuario_login ?>"><?= $comentario->usuario_login ?></a> a <?= $comentario->fecha ?>
            </div>
        <?php endforeach ?>
    </div>
<?php endif ?>



<?php Ti::endBlock(); ?>
<?php Ti::endExtend() ?>