<?php

use \dawfony\Ti;

extract($data);
global $URL_PATH;
Ti::extend("view/MainView.phtml"); ?>

<?php Ti::startBlock("content"); ?>
<h2>Estás siguiendo a: </h2>
<ul class="list-group list-group-horizontal">
    <?php foreach ($siguiendo as $usuario) : ?>
        <li class="list-group-item"><?= $usuario["usuario_login_seguido"] ?></li>
    <?php endforeach ?>
</ul>

<?php Ti::endBlock(); ?>
<?php Ti::endExtend() ?>