<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Borrado</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <h3 class="mb-1 display-3">Plantas</h3>
        <div class="jumbotron">
            <h1 class="display-4">Confirmación de borrado</h1>
            <p>¿Seguro que desea borrar la planta <?= $planta->nombre ?>?</p>
            <a class="btn btn-primary btn-lg" href="?controller=borrar&id=<?= $planta->id ?>&borrado=si" role="button">Sí</a>
            <a class="btn btn-info btn-lg" href="?controller=listar" role="button">No. Volver al listado</a>
        </div>
    </div>
</body>

</html>