<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Listado</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>

    <div class="container">
        <h3 class="mb-1 display-3">Plantas</h3>
        <a class="btn btn-primary btn-lg" href="?controller=insertar" role="button">Insertar Planta</a>
        <table class="table table-striped table-hover mt-3">
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Precio</th>
                <th>Ambiente</th>
                <th>Riego</th>
                <th></th>
            </tr>
            <?php foreach ($plantas as $planta) : ?>
                <tr>
                    <th scope="row"><?= $planta->id ?></th>
                    <td><?= $planta->nombre ?></td>
                    <td><?= $planta->precio ?></td>
                    <?php if ($planta->ambiente == "E") : ?>
                        <td>Exterior</td>
                    <?php endif ?>
                    <?php if ($planta->ambiente == "I") : ?>
                        <td>Interior</td>
                    <?php endif ?>
                    <?php if ($planta->ambiente == "M") : ?>
                        <td>Mixto</td>
                    <?php endif ?>
                    <td><?= printf("%.1f", $planta->riego()) ?> l/semana</td>
                    <td><a href="?controller=borrar&id=<?= $planta->id ?>" class="btn btn-danger" role="button">Borrar</a></td>
                </tr>
            <?php endforeach ?>
        </table>

    </div>

</body>

</html>